variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  - stage: run
    displayName: Run
    jobs:
      - deployment: runTerragrunt
        displayName: Run Terragrunt
        pool:
          vmImage: ${{variables.vmImage}}
        environment: aaa
        variables:
          - name: terraformOutputDir
            value: $(Agent.TempDirectory)/tfplan-$(Build.BuildId)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - checkout: stuartellis-org-tf-modules

                - template: .azure-pipelines/setup-binaries.yml
                  parameters:
                    workingDirectory: ${{ variables.name }}

                - template: .azure-pipelines/compile-tf-plan.yml
                  parameters:
                    awsRegion: eu-west-1
                    awsServiceConnection: sje-aws-origin
                    projectName: ${{ variables.name }}
                    tfLogLevel: ${{ variables.tfLogLevel }}
                    terraformOutputDir: $(Agent.TempDirectory)/tfplan-$(Build.BuildId)/aws-sjeo-aaa-useast1-s-n
                    terraformSourceStackDir: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/live/aws/stuartellis-origin/$(Environment.Name)/us-east-1/shared/notifications
                    terragruntExe: $(Build.Repository.LocalPath)/${{ variables.name }}/bin/terragrunt

                - ${{ if eq(variables.dryRun, false) }}:
                    - template: .azure-pipelines/apply-tf-plan.yml
                      parameters:
                        awsRegion: eu-west-1
                        awsServiceConnection: sje-aws-origin
                        projectName: ${{ variables.name }}
                        tfLogLevel: ${{ variables.tfLogLevel }}
                        terraformOutputDir: $(Agent.TempDirectory)/tfplan-$(Build.BuildId)/aws-sjeo-aaa-useast1-s-n
                        terraformSourceStackDir: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/live/aws/stuartellis-origin/$(Environment.Name)/us-east-1/shared/notifications
                        terragruntExe: $(Build.Repository.LocalPath)/${{ variables.name }}/bin/terragrunt

                - template: .azure-pipelines/archive-tf-plan.yml
                  parameters:
                    terraformOutputDir: $(Agent.TempDirectory)/tfplan-$(Build.BuildId)/aws-sjeo-aaa-useast1-s-n
