variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  - stage: run
    displayName: Run
    jobs:
      - job: run
        displayName: Run Terragrunt
        pool:
          vmImage: ${{variables.vmImage}}
        steps:
          - checkout: self
          - checkout: stuartellis-org-tf-modules
          - template: .azure-pipelines/setup-binaries.yml
            parameters:
              cacheKeyFile: stuartellis-org-infra/package.json
              cacheName: bin
              workingDirectory: stuartellis-org-infra
          - template: .azure-pipelines/run-terragrunt.yml
            parameters:
              awsRegion: eu-west-1
              awsServiceConnection: sje-aws-origin
              tgCommand: run-all validate
              workingDirectory: stuartellis-org-infra/tf/live/aws/stuartellis-origin
          - template: .azure-pipelines/run-terragrunt.yml
            parameters:
              awsRegion: eu-west-1
              awsServiceConnection: sje-aws-origin
              tgCommand: run-all plan
              workingDirectory: stuartellis-org-infra/tf/live/aws/stuartellis-origin
