variables:
  - template: .azure-pipelines/variables.yml

  - name: dryRun
    value: "true"

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  - stage: run
    displayName: Run
    jobs:
      - deployment: runTerragrunt
        displayName: Run Terragrunt
        pool:
          vmImage: ${{variables.vmImage}}
        environment: aaa
        variables:
          - name: terraformPlanDir
            value: $(Agent.TempDirectory)/tfplan-$(Build.BuildId)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - checkout: stuartellis-org-tf-modules

                - template: .azure-pipelines/setup-binaries.yml
                  parameters:
                    cacheKeyFile: ${{ variables.name }}/package.json
                    cacheName: binaries
                    workingDirectory: ${{ variables.name }}

                - template: .azure-pipelines/deploy-terragrunt-stack.yml
                  parameters:
                    awsRegion: eu-west-1
                    awsServiceConnection: sje-aws-origin
                    dryRun: ${{ variables.dryRun }}
                    projectName: ${{ variables.name }}
                    terraformPlanDir: $(Agent.TempDirectory)/tfplan-$(Build.BuildId)/aws-sjeo-aaa-useast1-s-n
                    terraformStackDir: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/live/aws/stuartellis-origin/${{ Environment.Name }}/us-east-1/shared/notifications
                    terragruntExe: $(Build.Repository.LocalPath)/${{ variables.name }}/bin/terragrunt
