variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  - stage: run
    displayName: Run
    jobs:
      - job: run
        displayName: Setup Binaries
        pool:
          vmImage: ${{variables.vmImage}}
        steps:
          - checkout: self
          - checkout: stuartellis-org-tf-modules
          - template: .azure-pipelines/setup-binaries.yml
            parameters:
              cacheKeyFile: stuartellis-org-infra/package.json
              toolName: terragrunt
              workingDirectory: stuartellis-org-infra
          # - template: .azure-pipelines/run-terragrunt.yml
          #   parameters:
          #     tgCommand: run-all plan
          #     tgSource: ../../../../../../../../../stuartellis-org-tf-modules
