variables:
  - template: .azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  - stage: run
    displayName: Run
    jobs:
      - job: run
        displayName: Run Terragrunt
        pool:
          vmImage: ${{variables.vmImage}}
        steps:
          - checkout: self
          - checkout: stuartellis-org-tf-modules

          - template: .azure-pipelines/setup-binaries.yml
            parameters:
              cacheKeyFile: stuartellis-org-infra/package.json
              cacheName: bin
              workingDirectory: stuartellis-org-infra

          - template: .azure-pipelines/run-terragrunt.yml
            parameters:
              awsRegion: eu-west-1
              awsServiceConnection: sje-aws-origin
              tgCommand: validate
              tgExe: $(Pipeline.Workspace)/stuartellis-org-infra/bin/terragrunt
              workingDirectory: tf/live/aws/stuartellis-origin/aaa/us-east-1/shared/notifications

          - template: .azure-pipelines/run-terragrunt.yml
            parameters:
              awsRegion: eu-west-1
              awsServiceConnection: sje-aws-origin
              tgCommand: plan
              tgOptions: "-out $(Agent.TempDirectory)/tfplan"
              tgExe: $(Pipeline.Workspace)/stuartellis-org-infra/bin/terragrunt
              workingDirectory: tf/live/aws/stuartellis-origin/aaa/us-east-1/shared/notifications

          - template: .azure-pipelines/run-terragrunt.yml
            parameters:
              awsRegion: eu-west-1
              awsServiceConnection: sje-aws-origin
              tgCommand: show
              tgOptions: "-json $(Agent.TempDirectory)/tfplan > $(Agent.TempDirectory)/tf-plan.json"
              tgExe: $(Pipeline.Workspace)/stuartellis-org-infra/bin/terragrunt
              workingDirectory: tf/live/aws/stuartellis-origin/aaa/us-east-1/shared/notifications

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: $(Agent.TempDirectory)
              artifactName: tfplan-$(System.JobId)
