AWSTemplateFormatVersion: "2010-09-09"
Description: |
  AWS resources for a Terraform backend

Parameters:
  Prefix:
    Type: String
    Description: The prefix for AWS resource names
  ReplicationBucketArn:
    Type: String
    Description: The ARN of the replica S3 bucket

Resources:
  TfBackendBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${Prefix}-tfstate-main-${AWS::AccountId}-${AWS::Region}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: sje:purpose
          Value: terraform-backend
      ReplicationConfiguration:
        Role: !GetAtt TfBackendBucketReplicationRole.Arn
        Rules:
          - Destination:
              Bucket: !Ref ReplicationBucketArn
            Id: ReplicationRule
            Prefix: ""
            Status: Enabled

  TfBackendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TfBackendBucket
      PolicyDocument:
        Statement:
          - Sid: Deny deletion of objects
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:DeleteObject"
            Resource: !Sub "${TfBackendBucket.Arn}/*"
          - Sid: Deny requests that do not use TLS
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:*"
            Resource: !Sub "${TfBackendBucket.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": "false"
          - Sid: Deny object uploads not using default encryption settings
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:PutObject"
            Resource: !Sub "${TfBackendBucket.Arn}/*"
            Condition:
              # The Null-condition allows uploads without encryption information in the request
              # (i.e., requests with default S3 bucket encryption) and the
              # StringNotEquals-condition denies uploads with invalid encryption information.
              # Note that using StringNotEqualsIfExists doesn’t work for uploads without encryption information.
              # The condition evaluates to true and denies the upload because of the Deny-effect.
              "Null":
                s3:x-amz-server-side-encryption: false
              StringNotEqualsIfExists:
                s3:x-amz-server-side-encryption:
                  - "AES256"
                  - "aws:kms"

  TfBackendBucketReplicationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: s3-replication-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetReplicationConfiguration"
                  - "s3:GetObjectVersionForReplication"
                  - "s3:GetObjectVersionAcl"
                Resource:
                  - !Sub "arn:${AWS::Partition}:s3:::${Prefix}-tfstate-main-${AWS::AccountId}-${AWS::Region}"
                  - !Sub "arn:${AWS::Partition}:s3:::${Prefix}-tfstate-main-${AWS::AccountId}-${AWS::Region}/*"
              - Effect: Allow
                Action:
                  - "s3:ReplicateObject"
                  - "s3:ReplicateDelete"
                  - "s3:ReplicateTags"
                  - "s3:GetObjectVersionTagging"
                  - "s3:GetBucketVersioning"
                  - "s3:PutBucketVersioning"
                Resource:
                  - !Ref ReplicationBucketArn
                  - !Sub "${ReplicationBucketArn}/*"

  TfBackendDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub ${Prefix}-tfstate-lock-${AWS::Region}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: sje:purpose
          Value: terraform-backend

Outputs:
  TfBackendBucket:
    Value: !GetAtt TfBackendBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-s3-state-arn"
  TfBackendDynamoDbTable:
    Value: !GetAtt TfBackendDynamoDbTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ddb-lock-arn"
