AWSTemplateFormatVersion: "2010-09-09"
Description: |
  AWS resources for a Terraform backend

Parameters:
  Prefix:
    Type: String
    Description: The prefix for AWS resource names

Resources:
  TfBackendDynamoDbTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub ${Prefix}-tfstate-lock-${AWS::Region}
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: sje:purpose
          Value: terraform-backend

Outputs:
  TfBackendDynamoDbTable:
    Value: !GetAtt TfBackendDynamoDbTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ddb-lock-arn"
