AWSTemplateFormatVersion: "2010-09-09"
Description: |
  AWS resources for executing Terraform execution 
Parameters:
  Prefix:
    Type: String
    Description: The prefix for AWS resource names
  ManagedPolicyName:
    Type: String
    Default: AdministratorAccess
    Description: The name of the IAM policy to apply
  ManagingAccountID:
    Type: Number
    Description: AWS account number that uses this role

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Prefix}-tf-exec
      Description: !Sub Terraform execution for ${Prefix}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: "Allow"
            Principal: 
              AWS: !Sub "arn:${AWS::Partition}:iam::${ManagingAccountID}:root"
            Action: 
              - "sts:AssumeRole"
      Tags:
        - Key: sje:purpose
          Value: terraform-execution
      ManagedPolicyArns: 
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/${ManagedPolicyName}"

Outputs:
  ExecutionRole:
    Value: !Ref ExecutionRole
