parameters:
  - name: dryRun
    displayName: Dry run only
    type: boolean
    default: true
  - name: terraformStacks
    displayName: Terraform stacks
    type: object
    default:
      ops-parameters: ops-parameters
      notifications: notifications

variables:
  - template: ../../../../.azure-pipelines/variables.yml

name: ${{variables.name}}-live-monitoring-aws-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - master
      - develop # FIXME: Remove this
  paths:
    include:
      - tf/live/aws/*/*/monitoring/**
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/master

stages:
  # Stacks for DEV AWS us-east-1 "shared"
  - template: ../../../../.azure-pipelines/deploy-tf-stack-group.yml
    parameters:
      stageName: dev
      environment: dev
      providerName: aws
      providerServiceConnection: sje-aws-tf
      cloudRegion: us-east-1
      dryRun: ${{ parameters.dryRun }}
      projectName: ${{ variables.name }}
      runIdentifier: tf-live-aws-dev-stuartellis-origin-monitoring-us-east-1-shared-$(Build.BuildId)
      stackGroupPath: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/live/aws/dev/stuartellis-origin/monitoring/us-east-1/shared
      vmImage: ${{ variables.vmImage }}
      terraformModulesRepo: stuartellis-org-tf-modules
      terraformStacks: ${{ parameters.terraformStacks }}

  # Stacks for QA AWS us-east-1 "shared"
  - template: ../../../../.azure-pipelines/deploy-tf-stack-group.yml
    parameters:
      stageName: qa
      previousStage: dev
      environment: qa
      providerName: aws
      providerServiceConnection: sje-aws-tf
      cloudRegion: us-east-1
      dryRun: ${{ parameters.dryRun }}
      projectName: ${{ variables.name }}
      runIdentifier: tf-live-aws-qa-stuartellis-origin-monitoring-us-east-1-shared-$(Build.BuildId)
      stackGroupPath: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/live/aws/qa/stuartellis-origin/monitoring/us-east-1/shared
      vmImage: ${{ variables.vmImage }}
      terraformModulesRepo: stuartellis-org-tf-modules
      terraformStacks: ${{ parameters.terraformStacks }}

  # Stacks for PROD AWS us-east-1 "shared"
  - template: ../../../../.azure-pipelines/deploy-tf-stack-group.yml
    parameters:
      stageName: prod
      previousStage: qa
      environment: prod
      providerName: aws
      providerServiceConnection: sje-aws-tf
      cloudRegion: us-east-1
      dryRun: ${{ parameters.dryRun }}
      projectName: ${{ variables.name }}
      runIdentifier: tf-live-aws-prod-stuartellis-origin-monitoring-us-east-1-shared-$(Build.BuildId)
      stackGroupPath: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/live/aws/prod/stuartellis-origin/monitoring/us-east-1/shared
      vmImage: ${{ variables.vmImage }}
      terraformModulesRepo: stuartellis-org-tf-modules
      terraformStacks: ${{ parameters.terraformStacks }}
