parameters:
  - name: dryRun
    displayName: Dry run only
    type: boolean
    default: false
  - name: terraformStacks
    displayName: Terraform stacks
    type: object
    default:
      dummy_s1: dummy_s1
      dummy_s2: dummy_s2

variables:
  - template: ../../../../.azure-pipelines/variables.yml

  - name: cloudAccount
    value: stuartellis-origin

  - name: productLine
    value: archives_pl

  - name: product
    value: archives_stacks

name: ${{variables.name}}-live-${{ variables.productLine }}-aws-${{ variables.product }}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop # FIXME: Remove this
  paths:
    include:
      - tf/live/aws/*/*/archives_pl/**
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: shared
      type: git
      name: azdo-shared-tasks
      ref: refs/heads/main
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  - template: pipeline-templates/terraform/deploy-tf-stack-group-aws.yml@shared
    parameters:
      stageName: dev
      environment: dev
      providerName: aws
      tfStorageServiceConnection: sje-aws-origin-tf
      tfStorageCloudRegion: eu-west-1
      dryRun: ${{ parameters.dryRun }}
      runIdentifier: tf-live-aws-dev-${{ variables.cloudAccount }}-${{ variables.productLine }}-eu-west-1-${{ variables.product }}-$(Build.BuildId)
      stackGroupPath: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/live/aws/dev/${{ variables.cloudAccount }}/${{ variables.productLine }}/eu-west-1/${{ variables.product }}
      vmImage: ${{ variables.vmImage }}
      terraformConfigDir: $(Build.Repository.LocalPath)/$(Build.Repository.Name)
      terraformInstallationDir: $(Agent.TempDirectory)
      terraformModulesRepo: stuartellis-org-tf-modules
      terraformStacks: ${{ parameters.terraformStacks }}
