parameters:
  - name: dryRun
    displayName: Dry run only
    type: boolean
    default: false
  - name: stackTeardown
    displayName: Teardown stacks
    type: boolean
    default: false
  - name: terraformStacks
    displayName: Terraform stacks
    type: object
    default:
      ops-parameters: ops-parameters
      notifications: notifications

variables:
  - template: ../../../../.azure-pipelines/variables.yml

name: ${{variables.name}}-ops-monitoring-aws-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - develop
      - feature/*
  paths:
    include:
      - tf/ops/aws/*/*/monitoring/**
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: shared
      type: git
      name: sje-ado-labs/azdo-shared-tasks
      ref: refs/heads/main
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  # Stacks for OPSLAB AWS us-east-1 "shared"
  - template: pipeline-templates/terraform/deploy-tf-stack-group.yml@shared
    parameters:
      stageName: opslab
      environment: opslab
      providerName: aws
      providerServiceConnection: sje-aws-tf
      cloudRegion: us-east-1
      dryRun: ${{ parameters.dryRun }}
      runIdentifier: tf-ops-aws-opslab-stuartellis-np-monitoring-us-east-1-shared-$(Build.BuildId)
      stackGroupPath: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/ops/aws/opslab/stuartellis-np/monitoring/us-east-1/shared
      stackTeardown: ${{ parameters.stackTeardown }}
      vmImage: ${{ variables.vmImage }}
      terraformConfigDir: $(Build.Repository.LocalPath)
      terraformInstallationDir: $(Agent.TempDirectory)
      terraformModulesRepo: stuartellis-org-tf-modules
      terraformStacks: ${{ parameters.terraformStacks }}
