parameters:
  - name: dryRun
    displayName: Dry run only?
    type: boolean
    default: true

variables:
  - template: ../../../../.azure-pipelines/variables.yml

name: ${{variables.name}}-$(Date:yyyyMMddhhmm).$(Rev:r)

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - CONTRIBUTING.md
      - README.md

resources:
  repositories:
    - repository: stuartellis-org-tf-modules
      type: git
      name: stuartellis-org-tf-modules
      ref: refs/heads/develop

stages:
  # Stacks for DEV AWS us-east-1 "shared"
  - template: ../../../../.azure-pipelines/run-tf-stack-group.yml
    parameters:
      environment: opslab
      providerName: aws
      providerServiceConnection: sje-aws-labs
      cloudRegion: us-east-1
      dryRun: ${{ parameters.dryRun }}
      projectName: ${{ variables.name }}
      runIdentifier: tf-opslab-aws-opslab-stuartellis-np-aaa-us-east-1-shared-$(Build.BuildId)
      stackGroupPath: $(Build.Repository.LocalPath)/${{ variables.name }}/tf/opslab/aws/opslab/stuartellis-np/aaa/us-east-1/shared
      vmImage: ${{ variables.vmImage }}
      terraformModulesRepo: stuartellis-org-tf-modules
      terraformStacks:
        notifications: notifications
