---
- name: Deploy CloudFormation for Terraform Storage
  hosts: localhost
  vars_prompt:
    - name: org_namespace
      prompt: Specify the namespace
      private: no
    - name: stack_prefix
      prompt: Specify the prefix for the stacks
      private: no
    - name: primary_region
      prompt: Specify the AWS region for primary storage
      private: no
    - name: secondary_region
      prompt: Specify the AWS region for secondary storage
      private: no

  tasks:
    - name: Stack for keys in secondary region
      register: kms_keys_secondary
      amazon.aws.cloudformation:
        stack_name: "{{ org_namespace }}-{{ stack_prefix }}-secondary-keys"
        region: "{{ secondary_region }}"
        state: "present"
        template: "../cloudformation/admin-account/tf-storage-replicated-kms/cfn-kms-keys.yml"
        template_parameters:
          KeyName0001: tfstate-secondary
          Prefix: "{{ stack_prefix }}"
        termination_protection: yes
        tags:
          "sje:source": ansible
          "sje:namespace": "{{ org_namespace }}"
          "sje:prefix": "{{ stack_prefix }}"

    - name: Stack for bucket in secondary region
      register: s3_bucket_secondary
      amazon.aws.cloudformation:
        stack_name: "{{ org_namespace }}-{{ stack_prefix }}-secondary-s3"
        region: "{{ secondary_region }}"
        state: "present"
        capabilities: CAPABILITY_NAMED_IAM
        template: "../cloudformation/admin-account/tf-storage-replicated-kms/cfn-storage-s3-replica.yml"
        template_parameters:
          KmsReplicaKeyArn: "{{ kms_keys_secondary.stack_outputs.KmsKey0001Arn }}"
          Prefix: "{{ stack_prefix }}"
        termination_protection: yes
        tags:
          "sje:source": ansible
          "sje:namespace": "{{ org_namespace }}"
          "sje:prefix": "{{ stack_prefix }}"

    - name: Stack for keys in primary region
      register: kms_keys_primary
      amazon.aws.cloudformation:
        stack_name: "{{ org_namespace }}-{{ stack_prefix }}-primary-keys"
        region: "{{ primary_region }}"
        state: "present"
        template: "../cloudformation/admin-account/tf-storage-replicated-kms/cfn-kms-keys.yml"
        template_parameters:
          KeyName0001: tfstate-primary
          Prefix: "{{ stack_prefix }}"
        termination_protection: yes
        tags:
          "sje:source": ansible
          "sje:namespace": "{{ org_namespace }}"
          "sje:prefix": "{{ stack_prefix }}"

    - name: Stack for bucket in primary region
      amazon.aws.cloudformation:
        stack_name: "{{ org_namespace }}-{{ stack_prefix }}-primary-s3"
        region: "{{ primary_region }}"
        state: "present"
        capabilities: CAPABILITY_NAMED_IAM
        template: "../cloudformation/admin-account/tf-storage-replicated-kms/cfn-storage-s3-source.yml"
        template_parameters:
          KmsReplicaKeyArn: "{{ kms_keys_secondary.stack_outputs.KmsKey0001Arn }}"
          KmsSourceKeyArn: "{{ kms_keys_primary.stack_outputs.KmsKey0001Arn }}"
          Prefix: "{{ org_namespace }}-{{ stack_prefix }}"
          ReplicaBucketArn: "{{ s3_bucket_secondary.stack_outputs.ReplicaBucketArn }}"
          ReplicaBucketRegion: "{{ secondary_region }}"
        termination_protection: yes
        tags:
          "sje:source": ansible
          "sje:namespace": "{{ org_namespace }}"
          "sje:prefix": "{{ stack_prefix }}"

    - name: Stack for DynamoDB in primary region
      amazon.aws.cloudformation:
        stack_name: "{{ org_namespace }}-{{ stack_prefix }}-primary-ddb"
        region: "{{ primary_region }}"
        state: "present"
        template: "../cloudformation/admin-account/tf-storage-replicated-kms/cfn-tf-lock-ddb.yml"
        template_parameters:
          KmsKeyArn: "{{ kms_keys_primary.stack_outputs.KmsKey0001Arn }}"
          Prefix: "{{ org_namespace }}-{{ stack_prefix }}"
        termination_protection: yes
        tags:
          "sje:source": ansible
          "sje:namespace": "{{ org_namespace }}"
          "sje:prefix": "{{ stack_prefix }}"
