parameters:
  - name: cloudRegion
    type: string
  - name: providerName
    type: string
  - name: providerServiceConnection
    type: string
  - name: targetName
    type: string
  - name: terraformOutputDir
    type: string
  - name: terraformSourceStackDir
    type: string
  - name: terragruntExe
    type: string

steps:
  - template: run-terragrunt-cmd-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      tgCommand: apply
      tgOptions: "${{ parameters.terraformOutputDir }}/tfplan.out"
      tgExe: ${{ parameters.terragruntExe }}
      workingDirectory: ${{ parameters.terraformSourceStackDir }}
