parameters:
  - name: archiveName
    type: string
  - name: rootDir
    type: string

steps:
  - task: ArchiveFiles@2
    displayName: Create ZIP
    condition: succeededOrFailed()
    inputs:
      rootFolderOrFile: ${{ parameters.rootDir }}
      includeRootFolder: false
      archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.archiveName }}.zip

  - task: PublishPipelineArtifact@1
    displayName: Publish ZIP
    condition: succeededOrFailed()
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/${{ parameters.archiveName }}.zip
      artifactName: terraform-$(System.JobId)
