parameters:
  - name: prefix
    type: string
  - name: outputDir
    type: string

steps:
  - task: ArchiveFiles@2
    displayName: Create ZIP
    condition: succeededOrFailed()
    inputs:
      rootFolderOrFile: ${{ parameters.outputDir }}
      includeRootFolder: false
      archiveFile: $(Build.ArtifactStagingDirectory)/${{ parameters.prefix }}-$(Build.BuildId).zip

  - task: PublishPipelineArtifact@1
    displayName: Publish ZIP
    condition: succeededOrFailed()
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/${{ parameters.prefix }}-$(Build.BuildId).zip
      artifactName: terraform-$(System.JobId)
