parameters:
  - name: cloudRegion
    type: string
  - name: providerServiceConnection
    type: string
  - name: providerName
    type: string
  - name: targetName
    type: string
  - name: terraformOutputDir
    type: string
  - name: terraformSourceDir
    type: string
  - name: terragruntExe
    type: string

steps:
  # Generate Terraform plan file for stack
  - template: run-terragrunt-cmd-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      tgCommand: plan
      tgOptions: "-out ${{ parameters.terraformOutputDir }}/tfplan.out"
      tgExe: ${{ parameters.terragruntExe }}
      workingDirectory: ${{ parameters.terraformSourceDir }}

  # Export a JSON version of Terraform plan file
  - template: run-terragrunt-cmd-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      tgCommand: show
      tgOptions: "-json ${{ parameters.terraformOutputDir }}/tfplan.out > ${{ parameters.terraformOutputDir }}/tfplan.json"
      tgExe: ${{ parameters.terragruntExe }}
      workingDirectory: ${{ parameters.terraformSourceDir }}
