parameters:
  - name: sourceFolder
    type: string
  - name: outputDir
    type: string

steps:
  - task: CopyFiles@2
    displayName: Copy package.json
    inputs:
      sourceFolder: ${{ parameters.sourceFolder }}
      contents: package.json
      targetFolder: ${{ parameters.outputDir }}
