parameters:
  - name: awsRegion
    type: string
  - name: awsServiceConnection
    type: string
  - name: projectName
    type: string
  - name: terraformOutputDir
    type: string
  - name: terraformSourceStackDir
    type: string

steps:
  - template: ../../../.azure-pipelines/compile-tf-plan.yml
    parameters:
      awsRegion: ${{ parameters.awsRegion }}
      awsServiceConnection: ${{ parameters.awsServiceConnection }}
      projectName: ${{ parameters.projectName }}
      terraformOutputDir: ${{ parameters.terraformOutputDir }}
      terraformSourceStackDir: ${{ parameters.terraformSourceStackDir }}
      terragruntExe: $(Build.Repository.LocalPath)/${{ parameters.projectName }}/bin/terragrunt

  - ${{ if eq(variables.dryRun, false) }}:
      - template: ../../../.azure-pipelines/apply-tf-plan.yml
        parameters:
          awsRegion: ${{ parameters.awsRegion }}
          awsServiceConnection: ${{ parameters.awsServiceConnection }}
          terraformOutputDir: ${{ parameters.terraformOutputDir }}
          terraformSourceStackDir: ${{ parameters.terraformSourceStackDir }}
          terragruntExe: $(Build.Repository.LocalPath)/${{ parameters.projectName }}/bin/terragrunt
