parameters:
  - name: awsRegion
    type: string
  - name: awsServiceConnection
    type: string
  - name: dryRun
    type: boolean
  - name: environment
    type: string
  - name: projectName
    type: string
  - name: runIdentifier
    type: string
  - name: stackGroupPath
    type: string
  - name: terraformModulesRepo
    type: string
  - name: terraformStacks
    type: object
  - name: vmImage
    type: string

stages:
  - stage:
    displayName: Run Terraform
    dependsOn: testTerraformCode
    jobs:
      - deployment: runTerragrunt
        displayName: Run Terragrunt
        pool:
          vmImage: ${{ parameters.vmImage }}
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - checkout: ${{ parameters.terraformModulesRepo }}

                - template: setup-binaries.yml
                  parameters:
                    workingDirectory: ${{ parameters.projectName }}

                - ${{ each stack in parameters.terraformStacks }}:
                    - template: compile-tf-plan-aws.yml
                      parameters:
                        awsRegion: ${{ parameters.awsRegion }}
                        awsServiceConnection: ${{ parameters.awsServiceConnection }}
                        projectName: ${{ parameters.projectName }}
                        terraformOutputDir: $(Agent.TempDirectory)/${{ parameters.runIdentifier }}/${{ stack.Key }}
                        terraformSourceStackDir: ${{ parameters.stackGroupPath }}/${{ stack.Key }}
                        terragruntExe: $(Build.Repository.LocalPath)/${{ parameters.projectName }}/bin/terragrunt

                    - ${{ if eq(parameters.dryRun, false) }}:
                        - template: apply-tf-plan-aws.yml
                          parameters:
                            awsRegion: ${{ parameters.awsRegion }}
                            awsServiceConnection: ${{ parameters.awsServiceConnection }}
                            terraformOutputDir: $(Agent.TempDirectory)/${{ parameters.runIdentifier }}/${{ stack.Key }}
                            terraformSourceStackDir: ${{ parameters.stackGroupPath }}/${{ stack.Key }}
                            terragruntExe: $(Build.Repository.LocalPath)/${{ parameters.projectName }}/bin/terragrunt

                - template: archive-outputs.yml
                  parameters:
                    prefix: ${{ parameters.runIdentifier }}
                    rootDir: $(Agent.TempDirectory)/${{ parameters.runIdentifier }}
