parameters:
  - name: awsRegion
    type: string
  - name: awsServiceConnection
    type: string
  - name: tgCommand
    type: string
  - name: tgSource
    type: string
  - name: workingDirectory
    type: string

steps:
  - task: AWSShellScript@1
    displayName: Run Terragrunt ${{ parameters.tgCommand }}
    inputs:
      awsCredentials: ${{ parameters.awsServiceConnection }}
      regionName: ${{ parameters.awsRegion }}
      scriptType: inline
      inlineScript: |
        TF_IN_AUTOMATION=1
        TF_INPUT=0
        TERRAGRUNT_SOURCE=${{ parameters.tgSource }}
        ../../../../bin/terragrunt ${{ parameters.tgCommand }}
      disableAutoCwd: true
      workingDirectory: ${{ parameters.workingDirectory }}
