parameters:
  - name: awsRegion
    type: string
  - name: awsServiceConnection
    type: string
  - name: tgCommand
    type: string
  - name: tgSource
    type: string
  - name: workingDirectory
    type: string

steps:
  - task: AWSShellScript@1
    displayName: Run Terragrunt
    inputs:
      awsCredentials: ${{ parameters.awsServiceConnection }}
      regionName: ${{ parameters.awsRegion }}
      scriptType: "inline"
      inlineScript: ./bin/terragrunt ${{ parameters.tgCommand }} --terragrunt-source ${{ parameters.tgSource }}
      workingDirectory: ${{ parameters.workingDirectory }}
