parameters:
  - name: tgCommand
    type: string
  - name: tgSource
    type: string

steps:
  - bash: |
      ./bin/terragrunt ${{ parameters.tgCommand }} --terragrunt-source ${{ parameters.tgSource }}
    displayName: Run Terragrunt
    env:
      TF_IN_AUTOMATION: true
