parameters:
  - name: cloudRegion
    type: string
  - name: providerServiceConnection
    type: string
  - name: targetName
    type: string
  - name: cmdName
    type: string
  - name: cmdExe
    type: string
  - name: cmdOptions
    type: string
    default: ""
  - name: workingDirectory
    type: string

steps:
  - task: AWSShellScript@1
    displayName: Run ${{ parameters.cmdName }} for ${{ parameters.targetName }}
    inputs:
      awsCredentials: ${{ parameters.providerServiceConnection }}
      regionName: ${{ parameters.cloudRegion }}
      scriptType: inline
      inlineScript: |
        TF_IN_AUTOMATION=1
        TF_INPUT=0
        ${{ parameters.cmdExe }} ${{ parameters.cmdName }} ${{ parameters.cmdOptions }}
      disableAutoCwd: true
      workingDirectory: ${{ parameters.workingDirectory }}
