parameters:
  - name: awsRegion
    type: string
  - name: awsServiceConnection
    type: string
  - name: tgCommand
    type: string
  - name: tgExe
    type: string
  - name: tgOptions
    type: string
    default: ""
  - name: workingDirectory
    type: string

steps:
  - task: AWSShellScript@1
    displayName: Run Terragrunt ${{ parameters.tgCommand }}
    inputs:
      awsCredentials: ${{ parameters.awsServiceConnection }}
      regionName: ${{ parameters.awsRegion }}
      scriptType: inline
      inlineScript: |
        # TF_IN_AUTOMATION=1
        # TF_INPUT=0
        TF_LOG=DEBUG
        ${{ parameters.tgExe }} run ${{ parameters.tgCommand }} ${{ parameters.tgOptions }}
      disableAutoCwd: true
      workingDirectory: ${{ parameters.workingDirectory }}
