parameters:
  - name: workingDirectory
    type: string

steps:
  - bash: |
      ./do.sh setup
    displayName: Install tools
    workingDirectory: ${{ parameters.workingDirectory }}
  - bash: |
      ./do.sh info
    displayName: Show tool details
    workingDirectory: ${{ parameters.workingDirectory }}
