steps:
  - task: Cache@2
    inputs:
      key: ${{ parameters.toolName }} | "$(Agent.OS)" | package.json
      path: bin
    displayName: Use Cache for binaries
  - bash: |
      ./do.sh setup
    displayName: Run setup
  - bash: |
      ./do.sh info
    displayName: Show details
