parameters:
  - name: cacheKeyFile
    type: string
  - name: cacheName
    type: string
  - name: workingDirectory
    type: string

steps:
  - task: Cache@2
    inputs:
      key: ${{ parameters.cacheName }} | "$(Agent.OS)" | ${{ parameters.cacheKeyFile }}
      path: ${{ parameters.workingDirectory }}/bin
    displayName: Use cache for binaries
  - bash: |
      ./do.sh setup
    displayName: Run setup
    workingDirectory: ${{ parameters.workingDirectory }}
  - bash: |
      ./do.sh info
    displayName: Show details for setup
    workingDirectory: ${{ parameters.workingDirectory }}
