parameters:
  - name: workingDirectory
    type: string

steps:
  - bash: |
      ./do.sh setup
    displayName: Run setup
    workingDirectory: ${{ parameters.workingDirectory }}
  - bash: |
      ./do.sh info
    displayName: Show details for setup
    workingDirectory: ${{ parameters.workingDirectory }}
