parameters:
  - name: cloudRegion
    type: string
  - name: providerServiceConnection
    type: string
  - name: providerName
    type: string
  - name: targetName
    type: string
  - name: terraformOutputDir
    type: string
  - name: terraformSourceDir
    type: string
  - name: terraformExe
    type: string

steps:
  # Validate configuration for stack
  - template: run-tf-cmd-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      cmdName: validate
      cmdExe: ${{ parameters.terraformExe }}
      workingDirectory: ${{ parameters.terraformSourceDir }}
