parameters:
  - name: cloudRegion
    type: string
  - name: providerServiceConnection
    type: string
  - name: projectName
    type: string
  - name: providerName
    type: string
  - name: targetName
    type: string
  - name: terraformOutputDir
    type: string
  - name: terraformSourceDir
    type: string
  - name: terragruntExe
    type: string

steps:
  # Validate configuration for stack
  - template: run-terragrunt-cmd-${{ parameters.providerName }}.yml
    parameters:
      cloudRegion: ${{ parameters.cloudRegion }}
      providerServiceConnection: ${{ parameters.providerServiceConnection }}
      targetName: ${{ parameters.targetName }}
      tgCommand: validate
      tgExe: ${{ parameters.terragruntExe }}
      workingDirectory: ${{ parameters.terraformSourceDir }}
