variables:
  - name: name
    value: stuartellis-org-infra
  - name: dryRun
    value: "true"
  - name: tfLogLevel
    value: INFO # Options are: TRACE, DEBUG, INFO, WARN, ERROR
  - name: vmImage
    value: ubuntu-20.04
